version: '3.1'
services:
  shipments:
    container_name: shipments
    build: .
    ports:
      - '8080:8080'
    environment:
      ENVIRONMENT: "docker"
      DB_HOST: shipmentsdb
      DB_PORT: 3306
      DB_USER: send_user
      DB_PASSWORD: p@azzword
      DB_NAME: shipments

    depends_on:
      shipmentsdb:
        condition: service_healthy

    networks:
      - shipments


  shipmentsdb:
    container_name: shipments-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: send_user
      MYSQL_PASSWORD: p@azzword
      MYSQL_DATABASE: shipments

    networks:
      - shipments

    healthcheck: # check the healthiness with the following configuration
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=zssn_user', '--password=p@azzword']
      interval: 3s
      timeout: 3s
      retries: 5

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - shipments

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./deployments/loki/config.yml:/etc/promtail/promtail-config.yaml
    networks:
      - shipments
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - shipments
    depends_on:
      - loki

networks:
  shipments:
    driver: bridge
    