version: '3.7'
x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
services:
  shipments:
    container_name: shipments
    logging: *loki-logging
    build: .
    ports:
      - '8080:8080'
    environment:
      ENVIRONMENT: "docker"
      DB_HOST: shipmentsdb
      DB_PORT: 3306
      DB_USER: send_user
      DB_PASSWORD: p@azzword
      DB_NAME: shipments
      OTLP_ENDPOINT: tempo:4318

    depends_on:
      shipmentsdb:
        condition: service_healthy

    networks:
      - shipments

  shipmentsdb:
    container_name: shipments-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    logging: *loki-logging
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: send_user
      MYSQL_PASSWORD: p@azzword
      MYSQL_DATABASE: shipments

    networks:
      - shipments

    healthcheck: # check the healthiness with the following configuration
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=zssn_user', '--password=p@azzword']
      interval: 3s
      timeout: 3s
      retries: 5

  loki:
    image: grafana/loki:latest
    container_name: shipments-loki
    command: -config.file=/mnt/config/loki-config.yaml
    logging: *loki-logging
    volumes:
      - ./loki/loki-config.yaml:/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - shipments

  promtail:
    image: grafana/promtail:latest
    container_name: shipments-promtail
    volumes:
      - ./loki/promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/lib/docker/containers:/host/containers
    command: -config.file /mnt/config/promtail-config.yaml
    logging: *loki-logging
    networks:
      - shipments
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: shipments-grafana
    logging: *loki-logging
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - shipments
    depends_on:
      - loki
      - promtail
#      - tempo

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo-data:/var/tempo

  tempo:
    image: *tempoImage
    container_name: shipments-tempo
    logging: *loki-logging
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"  # zipkin

    depends_on:
      - init

    networks:
        - shipments

volumes:
  shipmentsdb_data:
    driver: local

  loki_data:
    driver: local

  promtail_data:
    driver: local

  tempo-data:
    driver: local

networks:
  shipments:
    driver: bridge
    