services:
  shipments:
    container_name: shipments
    build: .
    ports:
      - '8080:8080'
    environment:
      ENVIRONMENT: "docker"
      DB_HOST: shipmentsdb
      DB_PORT: 3306
      DB_USER: send_user
      DB_PASSWORD: p@azzword
      DB_NAME: shipments
      OTEL_EXPORTER_OTLP_INSECURE: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-lgtm:4318
      OTEL_METRIC_EXPORT_INTERVAL: "5000"

    depends_on:
      shipmentsdb:
        condition: service_healthy

    networks:
      - shipments

  shipmentsdb:
    container_name: shipments-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: send_user
      MYSQL_PASSWORD: p@azzword
      MYSQL_DATABASE: shipments

    networks:
      - shipments

    healthcheck: # check the healthiness with the following configuration
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=zssn_user', '--password=p@azzword']
      interval: 3s
      timeout: 3s
      retries: 5

  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: shipment-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
    volumes:
      - grafana:/data/grafana
      - prom-data:/data/prometheus
      - loki_data:/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
    networks:
      - shipments

volumes:
  shipmentsdb_data:
    driver: local

  grafana:
    driver: local

  loki_data:
    driver: local

  prom-data:
    driver: local

networks:
  shipments:
    driver: bridge
    